### ISSUE TITLE
capturing driver sigsegv's ?

### ISSUE THREAD

**Issue by sokoow** [nccgroup/TriforceLinuxSyscallFuzzer#1]
Hey, I've been running this on 4.6.5-rt for quite a while now. Didn't find any kernel crashes luckily, but got some interesting driver app crashes:

```
id 5909 time 1471281654.181486
driver[124]: segfault at 444ca9 ip 0000000000444ca9 sp 00007ffe63d40708 error 14

pid 5973 time 1471281654.597445
driver[124]: segfault at 6d1bd4 ip 00000000004010a4 sp 00007ffe63d40770 error 4 in driver[400000+d0000]
driver[124]: segfault at 6d1bd4 ip 00000000004010a4 sp 00007ffe63d40770 error 4 in driver[400000+d0000]
```

Now I didn't isolate inputs that do it, but I'd be curious to dig deeper into the in order to make driver more robust. How would I do that ? Does it make any sense ?

**Comment by timnewsham** [comment]
This might not be the fault of the driver program.  Because the driver program is running arbitrary system calls, it can invoke system calls that cause a segfault at times.  You should start analyzing the cases to see what the root cause is by running "driver -tvx < crashfile" (with -x) on a linux box you have handy to see what the system call is, or by running "driver -tv < crashfile" (without -x) inside of the AFL qemu system to reproduce the crash while you have a debugger attached to qemu, so explore the crash further.

My hunch is that you have a test call which called the "clone" system call which caused it to jump to an unmapped address or to jump to an existing code address and use the registers in an unexpected way.

**Comment by jessemtso** [comment]
feel free to reopen this, or email tim or myself if you have more questions
